# use this for standard usage and development.

version: '3.3'

services:
  countr:
    container_name: countr
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URI=mongodb://db/countr
      - API_URI=http://manager:$API_PORT
    volumes:
      - ./logs/countr:/app/logs
    depends_on:
      - manager
      - db
  manager:
    container_name: manager
    build: .
    restart: always
    command: ["npm", "run", "manager"]
    environment:
      - DATABASE_URI=mongodb://db/countr
    volumes:
      - ./logs/manager:/app/logs
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - db
  db:
    container_name: db
    image: mongo:4
    restart: always
    volumes:
      - ./database:/data/db