# use this file for development and testing purposes
version: '3.3'

services:
  countr:
    build: .
    container_name: countr
    restart: unless-stopped
    environment:
      - DATABASE_URI=mongodb://db/countr
      - MANAGER_URI=http://manager:1337
    volumes:
      - ./logs/countr:/app/logs
    depends_on:
      - manager
      - db
  manager:
    build: .
    command: ["npm", "run", "manager"]
    container_name: manager
    restart: unless-stopped
    environment:
      - MANAGER_PORT=1337
    volumes:
      - ./logs/manager:/app/logs
    ports:
      - "8080:8080"
  db:
    image: mongo:4
    container_name: db
    restart: unless-stopped
    volumes:
      - ./database:/data/db