# use this for standard usage

version: '3'

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URI=mongodb://db/countr
      - WEBSOCKET_INTERNAL_URI=ws://manager
    volumes:
      - ./logs/countr:/app/logs
    depends_on:
      - db
      - manager
  manager:
    build: .
    restart: always
    command: ["npm", "run", "start:manager"]
    environment:
      - DATABASE_URI=mongodb://db/countr
      - WEBSOCKET_INTERNAL_PORT=80
    volumes:
      - ./logs/manager:/app/logs
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - db
  db:
    image: mongo:4@sha256:1a5dc2f28111e4270d8d317a1b9afbf811a7080333b740d31f5e296e7f0983b7
    restart: always
    volumes:
      - ./database:/data/db
