# use this for standard usage

version: '3'

services:
  bot:
    build: .
    restart: always
    environment:
      - DATABASE_URI=mongodb://db/countr
      - WEBSOCKET_INTERNAL_URI=ws://manager
    volumes:
      - ./logs/countr:/app/logs
    depends_on:
      - db
      - manager
  manager:
    build: .
    restart: always
    command: "start:manager"
    environment:
      - DATABASE_URI=mongodb://db/countr
      - WEBSOCKET_INTERNAL_PORT=80
    volumes:
      - ./logs/manager:/app/logs
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - db
  db:
    image: mongo:4@sha256:3ed0b7c5a7724c291db27d8407861bc5db96fafe902a6e9dd4e7657a37a4a4ed
    restart: always
    volumes:
      - ./database:/data/db
