version: '3.3'

services:
  countr:
    build: .
    container_name: countr
    restart: unless-stopped
    environment:
      - IS_THIS_DOCKER_WITH_MONGO=yes
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    image: mongo:4
    container_name: db
    restart: unless-stopped
    volumes:
      - ./database:/data/db