# use this file for development and testing purposes
version: '3.3'

services:
  countr:
    build: .
    container_name: countr
    restart: unless-stopped
    environment:
      - DATABASE_URI=mongodb://db/countr
    depends_on:
      - db
  db:
    image: mongo:4
    container_name: db
    restart: unless-stopped
    volumes:
      - ./database:/data/db