# this is for the premium bot.

version: '3'

services:
  cluster0:
    image: countr/countr-premium:latest
    restart: always
    volumes:
      - ./logs/countr-cluster0:/app/logs
    environment:
      - IS_PREMIUM=true
      - ACCESS_ENABLED=true
    depends_on:
      - manager
    networks:
      - countr-db
    labels:
      io.portainer.accesscontrol.teams: "promise-solutions"
  manager:
    image: countr/countr-premium:latest
    restart: always
    command: "start:manager"
    volumes:
      - ./logs/manager:/app/logs
    ports:
      - 127.0.0.1:$API_PORT:$API_PORT
    networks:
      - countr-db
    labels:
      io.portainer.accesscontrol.teams: "promise-solutions"

networks:
  countr-db:
    name: countr-premium
    external: true
