# use this for Portainer

version: '3'

services:
  bot:
    image: countr/stack
    build: ..
    restart: always
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - BOT_ID=$BOT_ID
      - DATABASE_URI=mongodb://db/countr
      - OWNER=$OWNER
      - ADMINS=$ADMINS
      - GUILD=$GUILD
      - API_PORT=$API_PORT
      - API_NUMBER_OF_PROXIES=$API_NUMBER_OF_PROXIES
      - WEBSOCKET_INTERNAL_URI=ws://manager
      - COLOR_PRIMARY=$COLOR_PRIMARY
      - COLOR_SUCCESS=$COLOR_SUCCESS
      - COLOR_ERROR=$COLOR_ERROR
      - COLOR_WARNING=$COLOR_WARNING
      - COLOR_INFO=$COLOR_INFO
      - WEBHOOK_URL=$WEBHOOK_URL
      - IS_PREMIUM=$IS_PREMIUM
      - HASTEBIN_LINK=$HASTEBIN_LINK
    volumes:
      - ./logs/countr:/app/logs
    depends_on:
      - db
      - manager
  manager:
    image: countr/stack
    restart: always
    command: "start:manager"
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - BOT_ID=$BOT_ID
      - DATABASE_URI=mongodb://db/countr
      - OWNER=$OWNER
      - ADMINS=$ADMINS
      - GUILD=$GUILD
      - API_PORT=$API_PORT
      - API_NUMBER_OF_PROXIES=$API_NUMBER_OF_PROXIES
      - WEBSOCKET_INTERNAL_PORT=80
      - WEBSOCKET_INTERNAL_URI=ws://manager
      - COLOR_PRIMARY=$COLOR_PRIMARY
      - COLOR_SUCCESS=$COLOR_SUCCESS
      - COLOR_ERROR=$COLOR_ERROR
      - COLOR_WARNING=$COLOR_WARNING
      - COLOR_INFO=$COLOR_INFO
      - WEBHOOK_URL=$WEBHOOK_URL
      - IS_PREMIUM=$IS_PREMIUM
      - HASTEBIN_LINK=$HASTEBIN_LINK
    volumes:
      - ./logs/manager:/app/logs
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - db
  db:
    image: mongo:4@sha256:4dc218699ef9788a9370d57655b55bffda0c7a7e4f4af91a7aa1b542f929c10b
    restart: always
    volumes:
      - ./database:/data/db
