name: Analysis and Scans

on:
  push:
  pull_request:
  schedule:
    - cron: '0 12 * * 3'

jobs:
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Checkout head of pull request
      run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  ossar:
    name: OSSAR Analysis
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Checkout head of pull request
      run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}

    - name: Perform OSSAR analysis
      uses: github/ossar-action@v1
      id: analysis

    - name: Upload OSSAR results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.analysis.outputs.sarifFile }}

  docker:
    name: Docker Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Checkout head of pull request
      run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}

    - name: Build Docker image
      run: docker build . -t local/testimage:latest

    - name: Perform Docker scan
      uses: anchore/scan-action@v3
      with:
        image: "local/testimage:latest"
        acs-report-enable: true
      id: scan

    - name: Upload Docker results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}