name: Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3

    - name: Copy dummy .env file
      run: cp "./.docker/docker-test.env" "./.env"

    - name: Test docker compose build
      run: docker compose build
