name: Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

    - name: Copy dummy .env file
      run: cp "./.docker/docker-test.env" "./.env"

    - name: Test docker compose build
      run: docker compose build
