name: Docker Compose

on:
  push:
    branches:
      - djs-13
  pull_request:
    branches:
      - djs-13

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cp "docker/test.env" ".env"
    - run: docker compose build