name: Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

    - name: Add .env file
      run: echo "API_PORT=1234" > .env

    - name: Test docker compose build
      run: docker compose build
